const express = require('express')
const app = express()
const {check, validationResult } = require('express-validator')
const server = require('http').createServer(app)
const htmlRoutes = require('./htmlRoutes.js')
app.use(express.urlencoded({ extended: true}))
app.use(express.json())
app.use(htmlRoutes)
server.listen(4200)
