describe('Test', function()
{
    it('successfully loads', function()
    {
        cy.visit('http://localhost:3000')
        cy.contains('Login')
        cy.contains('Home')
        cy.contains('Signup')
        cy.contains('Signup').click()
        cy.url().should('include', '/signup')
        cy.contains('here').click()
        cy.url().should('include', '/login')
        cy.contains('Home').click()
        cy.url().should('include', '')
        cy.contains('Signup').click()
        cy.url().should('include', '/signup')
        cy.get('#email').type('CypressTest')
        cy.get('#password').type('CypressTest')
        cy.get('#confirmPassword').type('CypressTest')
        cy.get('#username').type('CypressTest')
        cy.contains('here').click()
    })
})
          
